global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'chat-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'app-1:8080'
          - 'app-2:8080'
        labels:
          group: 'chat-service'
